### ISSUE TITLE
When I try to generate more than 216 spheres, strange bugs happen when rendering

### ISSUE THREAD

**Issue by vicentecesar** [gamephysicsweekend/VulkanRenderer#2]
When I use the following code, everything works normally:

// Dynamic Bodies
for (int x = 0; x < 6; x++) {
      for (int y = 0; y < 6; y++) {
	      float radius = 0.5f;
	      float xx = float(x - 1) * radius * 2;
	      float yy = float(y - 1) * radius * 2;
	      body.m_position = Vec3(xx, yy, 10.0f);
	      body.m_orientation = Quat(0, 0, 0, 1);
	      body.m_linearVelocity.Zero();
	      body.m_invMass = 1.0f;
	      body.m_elasticity = 0.5f;
	      body.m_friction = 0.5f;
	      body.m_shape = new ShapeSphere(radius);
	      m_bodies.push_back(body);
      }
}

But if I change the limits from 6 to 15, it will happen:

![image](https://user-images.githubusercontent.com/39139583/117581413-01d11600-b0d3-11eb-8255-0c125934a0d1.png)

If I move the mouse, strange things happen ... What could be wrong?

Thank you for the excellent book!

**Comment by gamephysicsweekend** [comment]
Hey thanks for bringing up this issue.  My apologies for the tardy response.

What's your system?  Are you getting any vulkan errors from the validation layer?  The vulkan layers should be enabled by default.

Also, I'm surprised you're running with that many bodies without crashing.  In Scene::Update you probably need to replace alloca with malloc like so:

`contact_t * contacts = (contact_t *)malloc( sizeof( contact_t ) * maxContacts );`

and then don't forget to free it at the end of the function:

`free( contacts );`

I used alloca in the books because it's faster/easier to allocate memory on the stack instead of the heap.  But the stack will quickly run out of memory if you're creating that many bodies.  And on my home system, I crash the program with that many bodies.  Changing it to malloc/free will allow you to have lots more potential contacts between bodies.

To be explicitly verbose, here is how I had to modify the Scene::Update function to accommodate that many bodies:

```
void Scene::Update( const float dt_sec ) {
	// Gravity impulse
	for ( int i = 0; i < m_bodies.size(); i++ ) {
		Body * body = &m_bodies[ i ];
		float mass = 1.0f / body->m_invMass;
		Vec3 impulseGravity = Vec3( 0, 0, -10 ) * mass * dt_sec;
		body->ApplyImpulseLinear( impulseGravity );
	}

	//
	// Broadphase
	//
	std::vector< collisionPair_t > collisionPairs;
	BroadPhase( m_bodies.data(), (int)m_bodies.size(), collisionPairs, dt_sec );

	//
	//	NarrowPhase (perform actual collision detection)
	//
	int numContacts = 0;
	const int maxContacts = m_bodies.size() * m_bodies.size();
	//contact_t * contacts = (contact_t *)alloca( sizeof( contact_t ) * maxContacts );
	contact_t * contacts = (contact_t *)malloc( sizeof( contact_t ) * maxContacts );
	for ( int i = 0; i < collisionPairs.size(); i++ ) {
		const collisionPair_t & pair = collisionPairs[ i ];
		Body * bodyA = &m_bodies[ pair.a ];
		Body * bodyB = &m_bodies[ pair.b ];

		// Skip body pairs with infinite mass
		if ( 0.0f == bodyA->m_invMass && 0.0f == bodyB->m_invMass ) {
			continue;
		}

		contact_t contact;
		if ( Intersect( bodyA, bodyB, dt_sec, contact ) ) {
			contacts[ numContacts ] = contact;
			numContacts++;
		}
	}

	// Sort the times of impact from first to last
	if ( numContacts > 1 ) {
		qsort( contacts, numContacts, sizeof( contact_t ), CompareContacts );
	}

	//
	// Apply ballistic impulses
	//
	float accumulatedTime = 0.0f;
	for ( int i = 0; i < numContacts; i++ ) {
		contact_t & contact = contacts[ i ];
		const float dt = contact.timeOfImpact - accumulatedTime;

		// Position update
		for ( int j = 0; j < m_bodies.size(); j++ ) {
			m_bodies[ j ].Update( dt );
		}

		ResolveContact( contact );
		accumulatedTime += dt;
	}

	// Update the positions for the rest of this frame's time
	const float timeRemaining = dt_sec - accumulatedTime;
	if ( timeRemaining > 0.0f ) {
		for ( int i = 0; i < m_bodies.size(); i++ ) {
			m_bodies[ i ].Update( timeRemaining );
		}
	}

	free( contacts );
}
```
