### ISSUE TITLE
Game Physics in One Weekend Issue with angular velocity and friction?

### ISSUE THREAD

**Issue by frostpitt** [gamephysicsweekend/VulkanRenderer#3]
Hi,

Love the book and it's really helped me get some physics into my in development game engine.

I wanted to share that I think there is an issue in the angular velocity and friction example. My sphere never rotated whenever it impacted the ground and first I thought it was some mistake in my code with the calculation of angular velocity and the impulses but then I noticed you have the ground have its m_friction set to 0.0f. This makes total friction 0.

In my readings elsewhere, I believe that any contact where there is no friction for a sphere with its center of mass equal to that of its position would result in no rotations at all. Correct me if I am wrong here please as I am very new to game physics.

I had to set the ground friction to something other than 0.0f (I set it 1.0f) in order to achieve a result which looks realistic (at least to my eyes).

P.S - I could not find any contact information and anywhere else to share feedback or issues found in the book so posted it here. If this is not the right place, let me know.

**Comment by gamephysicsweekend** [comment]
Hey there!

First, I'm glad you're finding the book to be useful.

And yes, you need friction on both bodies, otherwise they would just slide without rolling.  Thanks for pointing out this error.  I'll be sure to correct it in the next update.

Also, this is a perfectly fine place to raise an issue, error correction, or just general questions.  If you want to ask in a more private way though, my personal twitter and an email address are listed in the overview section of the first book.

Cheers!
